// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoServer.Web.Context;

namespace Web.Migrations
{
  [DbContext(typeof(AppDbContext))]
  [Migration("20200908195853_Initial")]
  partial class Initial
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
          .HasAnnotation("ProductVersion", "3.1.6")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      modelBuilder.Entity("TodoServer.Web.Entities.User", b =>
          {
            b.Property<string>("Id")
                      .HasColumnType("text");

            b.Property<string>("Email")
                      .HasColumnType("text");

            b.Property<string>("FirstName")
                      .HasColumnType("text");

            b.Property<string>("LastName")
                      .HasColumnType("text");

            b.Property<string>("Password")
                      .HasColumnType("text");

            b.HasKey("Id");

            b.ToTable("Users");
          });
#pragma warning restore 612, 618
    }
  }
}
