// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoServer.Web.Context;

namespace Web.Migrations
{
  [DbContext(typeof(AppDbContext))]
  partial class AppDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
          .HasAnnotation("ProductVersion", "3.1.6")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      modelBuilder.Entity("TodoServer.Web.Entities.Task", b =>
          {
            b.Property<string>("Id")
                      .HasColumnType("text");

            b.Property<string>("Name")
                      .HasColumnType("text");

            b.Property<string>("UserId")
                      .HasColumnType("text");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.ToTable("Tasks");
          });

      modelBuilder.Entity("TodoServer.Web.Entities.Todo", b =>
          {
            b.Property<string>("Id")
                      .HasColumnType("text");

            b.Property<string>("Description")
                      .HasColumnType("text");

            b.Property<bool>("IsComplete")
                      .HasColumnType("boolean");

            b.Property<string>("Name")
                      .HasColumnType("text");

            b.Property<string>("TaskId")
                      .HasColumnType("text");

            b.HasKey("Id");

            b.HasIndex("TaskId");

            b.ToTable("Todos");
          });

      modelBuilder.Entity("TodoServer.Web.Entities.User", b =>
          {
            b.Property<string>("Id")
                      .HasColumnType("text");

            b.Property<string>("Email")
                      .HasColumnType("text");

            b.Property<string>("FirstName")
                      .HasColumnType("text");

            b.Property<string>("LastName")
                      .HasColumnType("text");

            b.Property<string>("Password")
                      .HasColumnType("text");

            b.HasKey("Id");

            b.ToTable("Users");
          });

      modelBuilder.Entity("TodoServer.Web.Entities.Task", b =>
          {
            b.HasOne("TodoServer.Web.Entities.User", "User")
                      .WithMany()
                      .HasForeignKey("UserId");
          });

      modelBuilder.Entity("TodoServer.Web.Entities.Todo", b =>
          {
            b.HasOne("TodoServer.Web.Entities.Task", "Task")
                      .WithMany()
                      .HasForeignKey("TaskId");
          });
#pragma warning restore 612, 618
    }
  }
}
